ALTER TABLE "product_images"
ADD COLUMN IF NOT EXISTS "filename" TEXT,
ADD COLUMN IF NOT EXISTS "mimeType" TEXT,
ADD COLUMN IF NOT EXISTS "size" INTEGER,
ADD COLUMN IF NOT EXISTS "data" BYTEA;

ALTER TABLE "commercial_product_images"
ADD COLUMN IF NOT EXISTS "filename" TEXT,
ADD COLUMN IF NOT EXISTS "mimeType" TEXT,
ADD COLUMN IF NOT EXISTS "size" INTEGER,
ADD COLUMN IF NOT EXISTS "data" BYTEA;
